### ISSUE TITLE
how to use Admin Panel activate user account

### ISSUE THREAD

**Issue by rogermayo182** [open-webui/docs#20]
After i lanuched the open-webui docker,open the website  and signed up on the login page,then when i login to the system,it show the following message:
**Account Activation Pending**
**Contact Admin for WebUI Access**
Your account status is currently pending activation. To access the WebUI, please reach out to the administrator. Admins can manage user statuses from the Admin Panel.

the question:
1, where is the Admin Panel
2,Admin account info

**Comment by tjbck** [comment]
Please refer to: https://docs.openwebui.com/getting-started/

**Comment by rogermayo182** [comment]
got any way to re-init the acount database?
