### ISSUE TITLE
help wanted: better doc (idiot-proof level)

### ISSUE THREAD

**Issue by tjbck** [open-webui/docs#44]
Hi guys! I've been noticing some people struggling with installation/update process for ollama-webui and I feel like it would be extremely helpful for a lot of people if we could have a more thorough documentation!

<img width="787" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/280c7bbd-f00e-4e3b-8857-1e190908e22c">

Unfortunately, I won't have much time this week and If anyone can get the ball rolling for this (so that I can focus on adding more features), It'll be greatly appreciated. Thanks in advance, guys!

**Comment by 0xThresh** [comment]
These docs feel pretty idiot-proof now: https://docs.openwebui.com/getting-started/

Gonna close this since no one has commented in four months, anyone can re-open if they disagree.
